// Generated by tools/fetch-pokemon.mjs
// DO NOT EDIT DIRECTLY - Roster of party guests
const POKEMON_GUESTS = [
  {
    "id": 25,
    "name": "Pikachu",
    "types": [
      "electric"
    ],
    "image": "assets/pokemon/25.png",
    "description": "A friendly electric mouse with red cheeks that store electricity and a lightning-bolt tail."
  },
  {
    "id": 6,
    "name": "Charizard",
    "types": [
      "fire",
      "flying"
    ],
    "image": "assets/pokemon/6.png",
    "description": "A mighty winged dragon that soars through the sky and breathes intensely hot flames."
  },
  {
    "id": 7,
    "name": "Squirtle",
    "types": [
      "water"
    ],
    "image": "assets/pokemon/7.png",
    "description": "A cheerful little turtle who withdraws into its shell to spray high-speed water blasts."
  },
  {
    "id": 1,
    "name": "Bulbasaur",
    "types": [
      "grass",
      "poison"
    ],
    "image": "assets/pokemon/1.png",
    "description": "A gentle forest friend carrying a plant seed on its back that drinks in sunshine to grow."
  },
  {
    "id": 94,
    "name": "Gengar",
    "types": [
      "ghost",
      "poison"
    ],
    "image": "assets/pokemon/94.png",
    "description": "A sneaky shadow prankster that hides in dark corners and loves to play playful tricks."
  },
  {
    "id": 133,
    "name": "Eevee",
    "types": [
      "normal"
    ],
    "image": "assets/pokemon/133.png",
    "description": "A fluffy companion with rare, flexible genetics that let it evolve into eight different forms."
  },
  {
    "id": 143,
    "name": "Snorlax",
    "types": [
      "normal"
    ],
    "image": "assets/pokemon/143.png",
    "description": "A massive, sleepy giant that enjoys long naps and only wakes up to eat a huge feast."
  },
  {
    "id": 55,
    "name": "Golduck",
    "types": [
      "water"
    ],
    "image": "assets/pokemon/55.png",
    "description": "A graceful swimmer whose forehead gem glows with mysterious psychic powers in deep water."
  },
  {
    "id": 128,
    "name": "Tauros",
    "types": [
      "normal"
    ],
    "image": "assets/pokemon/128.png",
    "description": "A spirited wild bull with three whipping tails that charges forward with unstoppable energy."
  },
  {
    "id": 157,
    "name": "Typhlosion",
    "types": [
      "fire"
    ],
    "image": "assets/pokemon/157.png",
    "description": "Rubbing its fiery neck fur generates scorching bursts and explosive volcano flames."
  },
  {
    "id": 160,
    "name": "Feraligatr",
    "types": [
      "water"
    ],
    "image": "assets/pokemon/160.png",
    "description": "A powerhouse water crocodile that intimidates rivals by snapping its immense jaws."
  },
  {
    "id": 448,
    "name": "Lucario",
    "types": [
      "fighting",
      "steel"
    ],
    "image": "assets/pokemon/448.png",
    "description": "A noble guardian that can sense the aura energy and feelings of others from miles away."
  },
  {
    "id": 658,
    "name": "Greninja",
    "types": [
      "water",
      "dark"
    ],
    "image": "assets/pokemon/658.png",
    "description": "A swift ninja frog that moves like lightning and crafts throwing stars from pure water."
  },
  {
    "id": 778,
    "name": "Mimikyu",
    "types": [
      "ghost",
      "fairy"
    ],
    "image": "assets/pokemon/778.png",
    "description": "A lonely ghost who made a cute rag costume to look like Pikachu and make new friends."
  },
  {
    "id": 909,
    "name": "Fuecoco",
    "types": [
      "fire"
    ],
    "image": "assets/pokemon/909.png",
    "description": "A laid-back fire croc with an apple-like head that basks on warm stones to charge its flame."
  },
  {
    "id": 959,
    "name": "Tinkaton",
    "types": [
      "fairy",
      "steel"
    ],
    "image": "assets/pokemon/959.png",
    "description": "A spunky fairy artisan that constructed an enormous 200-pound steel hammer to toss rocks."
  },
  {
    "id": 4,
    "name": "Charmander",
    "types": [
      "fire"
    ],
    "image": "assets/pokemon/4.png",
    "description": "A spunky lizard whose mood and vitality burn steadily at the tip of its fiery tail."
  },
  {
    "id": 149,
    "name": "Dragonite",
    "types": [
      "dragon",
      "flying"
    ],
    "image": "assets/pokemon/149.png",
    "description": "A kindhearted marine dragon that can fly faster than sound and rescues ships in storms."
  }
];

