import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const rootDir = path.resolve(__dirname, '..');

const assetsDir = path.join(rootDir, 'assets', 'pokemon');
const jsDir = path.join(rootDir, 'js');

fs.mkdirSync(assetsDir, { recursive: true });
fs.mkdirSync(jsDir, { recursive: true });

// Mixed roster of 18 iconic Pokemon across generations
const POKEMON_ROSTER_IDS = [
  25,  // Pikachu
  6,   // Charizard
  7,   // Squirtle
  1,   // Bulbasaur
  94,  // Gengar
  133, // Eevee
  143, // Snorlax
  55,  // Golduck
  128, // Tauros
  157, // Typhlosion
  160, // Feraligatr
  448, // Lucario
  658, // Greninja
  778, // Mimikyu
  909, // Fuecoco
  959, // Tinkaton
  4,   // Charmander
  149  // Dragonite
];

async function fetchWithRetry(url, retries = 3) {
  for (let attempt = 1; attempt <= retries; attempt++) {
    try {
      const res = await fetch(url);
      if (!res.ok) throw new Error(`HTTP ${res.status}: ${res.statusText}`);
      return res;
    } catch (err) {
      if (attempt === retries) throw err;
      await new Promise((resolve) => setTimeout(resolve, 1000 * attempt));
    }
  }
}

async function main() {
  console.log(`Starting download of ${POKEMON_ROSTER_IDS.length} Pokémon from PokéAPI...`);
  const guests = [];

  for (const id of POKEMON_ROSTER_IDS) {
    try {
      console.log(`Fetching Pokémon #${id}...`);
      const apiRes = await fetchWithRetry(`https://pokeapi.co/api/v2/pokemon/${id}`);
      const data = await apiRes.json();

      const name = data.name.charAt(0).toUpperCase() + data.name.slice(1);
      const types = data.types.map((t) => t.type.name);
      
      const officialArtworkUrl =
        data.sprites.other?.['official-artwork']?.front_default ||
        data.sprites.front_default;

      if (!officialArtworkUrl) {
        throw new Error(`No sprite found for ${name} (#${id})`);
      }

      const imgRes = await fetchWithRetry(officialArtworkUrl);
      const arrayBuffer = await imgRes.arrayBuffer();
      const buffer = Buffer.from(arrayBuffer);
      const filename = `${id}.png`;
      const filePath = path.join(assetsDir, filename);

      fs.writeFileSync(filePath, buffer);
      console.log(` Saved ${name} (#${id}) to assets/pokemon/${filename}`);

      guests.push({
        id,
        name,
        types,
        image: `assets/pokemon/${filename}`
      });
    } catch (err) {
      console.error(`Failed to fetch Pokémon #${id}:`, err.message);
    }
  }

  const jsContent = `// Generated by tools/fetch-pokemon.mjs
// DO NOT EDIT DIRECTLY - Roster of party guests
const POKEMON_GUESTS = ${JSON.stringify(guests, null, 2)};
`;

  fs.writeFileSync(path.join(jsDir, 'pokemon-data.js'), jsContent, 'utf-8');
  console.log(`\n Successfully generated js/pokemon-data.js with ${guests.length} Pokémon!`);
}

main().catch((err) => {
  console.error('Fatal error running fetch-pokemon:', err);
  process.exit(1);
});
